-- MySQL Script generated by MySQL Workbench
-- Tue Sep 15 17:03:50 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema starvan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema starvan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `starvan` DEFAULT CHARACTER SET utf8mb4 ;
USE `starvan` ;

-- -----------------------------------------------------
-- Table `starvan`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starvan`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_usuario_email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `uq_usuario_login` (`login` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `starvan`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starvan`.`administrador` (
  `id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_administrador_usuario`
    FOREIGN KEY (`id`)
    REFERENCES `starvan`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `starvan`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starvan`.`cliente` (
  `id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`id`)
    REFERENCES `starvan`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `starvan`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starvan`.`carrinho` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cliente_id` INT(11) NOT NULL,
  `data_criacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `valor_total` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_carrinho_cliente` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_carrinho_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `starvan`.`cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `starvan`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starvan`.`endereco` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `starvan`.`cliente_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starvan`.`cliente_endereco` (
  `cliente_id` INT(11) NOT NULL,
  `endereco_id` INT(11) NOT NULL,
  PRIMARY KEY (`cliente_id`, `endereco_id`),
  INDEX `fk_cliente_endereco_endereco` (`endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_endereco_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `starvan`.`cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cliente_endereco_endereco`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `starvan`.`endereco` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `starvan`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starvan`.`produto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `categoria` VARCHAR(100) NOT NULL,
  `tamanho` VARCHAR(30) NOT NULL,
  `cor` VARCHAR(50) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `imagem` VARCHAR(255) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `quantidade` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `starvan`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starvan`.`estoque` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `produto_id` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL DEFAULT 0,
  `estoque_minimo` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_estoque_produto` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `starvan`.`produto` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `starvan`.`item_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starvan`.`item_carrinho` (
  `carrinho_id` INT(11) NOT NULL,
  `produto_id` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`carrinho_id`, `produto_id`),
  INDEX `fk_item_carrinho_produto` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_carrinho_carrinho`
    FOREIGN KEY (`carrinho_id`)
    REFERENCES `starvan`.`carrinho` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_item_carrinho_produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `starvan`.`produto` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `starvan`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starvan`.`pedido` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cliente_id` INT(11) NOT NULL,
  `endereco_entrega_id` INT(11) NOT NULL,
  `data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `status` VARCHAR(30) NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `forma_pagamento` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_cliente` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_pedido_endereco` (`endereco_entrega_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `starvan`.`cliente` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_endereco`
    FOREIGN KEY (`endereco_entrega_id`)
    REFERENCES `starvan`.`endereco` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `starvan`.`item_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starvan`.`item_pedido` (
  `pedido_id` INT(11) NOT NULL,
  `produto_id` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`pedido_id`, `produto_id`),
  INDEX `fk_item_pedido_produto` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_pedido_pedido`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `starvan`.`pedido` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_item_pedido_produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `starvan`.`produto` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
